/**
 * The physics world: the set of bodies, the ground under them, and the one `step` call
 * that advances all of it.
 *
 * The ground is not a body. It is a height function supplied by whoever owns the terrain
 * — in this game, threeWorld's park/landuse extrusions — because the alternative is
 * either a single flat plane (wrong the moment a road climbs over a park) or thousands of
 * triangle colliders for a surface that is already described analytically. Contacts
 * against it are generated by sampling that function under each body's own geometry, and
 * rays against it are answered in one lookup when they are plumb (which every wheel's is)
 * and by marching otherwise — between them that covers everything the vehicles and the
 * knocked-over street furniture need.
 *
 * Street furniture is added as *static* bodies carrying an `anchorImpulse`: how much
 * momentum, in newton-seconds, it takes to tear that thing out of the pavement. Until
 * something arrives with more than that, the body costs a broadphase entry and nothing
 * else. When it does, the body is promoted to dynamic in the same tick as the impact, so
 * the hit that dislodged it is also the hit that throws it — a post that had to wait a
 * tick to become dynamic would visibly absorb the blow first and then fall over on its
 * own.
 */
import * as THREE from 'three';
import { boxCorners, collideBodies, makeContact, type ContactPoint, type Manifold } from './collision';
import { createBroadphase, type Broadphase } from './broadphase';
import { bodyCategory, categoriesInteract, colliderCentre, MASK_ALL, type Aabb } from './types';
import { raycastBody, type RayHit } from './raycast';
import { solveContacts } from './solver';
import {
  createBody,
  integratePosition,
  integrateVelocity,
  setBodyDynamic,
  updateBodyDerived,
  updateSleep,
  wakeBody,
  type RigidBody,
} from './rigidBody';
import type { RaycastVehicle } from './vehicle';

export type GroundHeight = (x: number, z: number, maxHeight?: number) => number;

export interface PhysicsWorldOptions {
  gravity?: number;
  /** Solver relaxation passes per tick. Eight is comfortably enough for the shallow
   * piles this world produces and is not close to being the frame's bottleneck. */
  iterations?: number;
  broadphaseCellSize?: number;
  /** Speed, in m/s, above which a body gets a ray-swept collision fallback alongside the
   * discrete one — see the `step` doc comment on `fastMovers`. Comfortably above the
   * car's unboosted top speed (26 m/s) and below boost's (150 m/s), so ordinary driving
   * never pays for it. */
  sweepThreshold?: number;
}

export interface PhysicsWorld {
  readonly gravity: THREE.Vector3;
  readonly ground: RigidBody;
  addBody(body: RigidBody): void;
  removeBody(body: RigidBody): void;
  /** Drops every body whose `userData.layer` matches — used to clear the previous
   * world's street furniture when a new one streams in. */
  removeLayer(layer: string): void;
  bodies(): readonly RigidBody[];
  /** The manifolds solved on the last step, for the debug overlay. */
  manifolds(): readonly Manifold[];
  setGroundHeight(height: GroundHeight): void;
  groundHeightAt(x: number, z: number, maxHeight?: number): number;
  raycast(
    origin: THREE.Vector3,
    direction: THREE.Vector3,
    maxDistance: number,
    ignore?: RigidBody | null,
    /** Restricts hits to bodies whose category is in this mask. Defaults to `MASK_ALL`,
     * so a wheel probe (which never passes one) sees everything as before; the debug
     * picker and inspection ray can pass a narrower mask to see only what they draw. */
    categoryMask?: number,
  ): RayHit | null;
  addVehicle(vehicle: RaycastVehicle): void;
  removeVehicle(vehicle: RaycastVehicle): void;
  step(dt: number): void;
  /** Called once for each static prop torn loose, with the body that just went dynamic. */
  onDislodge(listener: (body: RigidBody) => void): void;
}

/** Overlap under which a body is considered to be resting on the ground rather than in
 * it — matched to the solver's own slop so the two do not fight. */
const GROUND_CONTACT_SLOP = 0.01;
// Enough to recover a shallow penetration or climb a road ramp, below a deck's thickness.
const GROUND_SURFACE_REACH = 0.3;
/** How far apart ground samples are taken when marching a ray. Half a metre resolves
 * every landuse step this world has (the tallest is under four metres) without turning a
 * wheel cast into dozens of samples. */
const GROUND_RAY_STEP = 0.5;
/** Bisection steps used to pin down the crossing once it has been bracketed. Twelve
 * takes a half-metre bracket to about a tenth of a millimetre, which matters more than it
 * sounds: a suspension damper reads the *rate of change* of strut length, so quantising
 * the ground it stands on turns into force noise of a couple of kilonewtons. */
const GROUND_RAY_REFINEMENTS = 12;
/** Default for `PhysicsWorldOptions.sweepThreshold` — see its doc comment. */
const DEFAULT_SWEEP_THRESHOLD = 50;

export function createPhysicsWorld(options: PhysicsWorldOptions = {}): PhysicsWorld {
  const gravity = new THREE.Vector3(0, -(options.gravity ?? 9.81), 0);
  const iterations = options.iterations ?? 8;
  const sweepThreshold = options.sweepThreshold ?? DEFAULT_SWEEP_THRESHOLD;
  const broadphase: Broadphase = createBroadphase(options.broadphaseCellSize ?? 8);

  const all: RigidBody[] = [];
  const dynamics: RigidBody[] = [];
  const statics: RigidBody[] = [];
  const vehicles: RaycastVehicle[] = [];
  const dislodgeListeners: Array<(body: RigidBody) => void> = [];
  let staticsDirty = true;
  let solved: Manifold[] = [];
  let previousImpulses = new Map<string, number>();
  let groundHeight: GroundHeight = () => 0;

  // Stands in for the terrain in every manifold generated against it, so the solver has
  // an infinite-mass counterparty to push against without special-casing anything.
  const ground = createBody({
    id: 'physics:ground',
    type: 'static',
    colliders: [],
    friction: 0.95,
    restitution: 0.02,
  });

  const reindex = () => {
    statics.length = 0;
    dynamics.length = 0;
    for (const body of all) (body.type === 'static' ? statics : dynamics).push(body);
    broadphase.setStatic(statics);
    staticsDirty = false;
  };

  const groundHeightAt = (x: number, z: number, maxHeight = Infinity) => groundHeight(x, z, maxHeight);

  /** Every ground ray answers with the same four fields; only where and how far differ. */
  const groundHit = (point: THREE.Vector3, distance: number): RayHit => ({
    body: ground,
    distance,
    point,
    normal: groundNormalAt(point.x, point.z, point.y + GROUND_SURFACE_REACH).clone(),
  });

  /**
   * Marches the ray in fixed steps looking for the first sample that has passed below the
   * terrain, then bisects that interval. Exact for the flat and gently sloping ground this
   * world is mostly made of, and correct to a few millimetres at a landuse step.
   */
  const raycastGround = (
    origin: THREE.Vector3,
    direction: THREE.Vector3,
    maxDistance: number,
  ): RayHit | null => {
    // A plumb ray — which every wheel's is — crosses only one column of terrain, so the
    // answer is exact in one lookup and there is nothing to march or bisect.
    if (Math.abs(direction.x) < 1e-6 && Math.abs(direction.z) < 1e-6 && direction.y < 0) {
      const distance = origin.y - groundHeightAt(origin.x, origin.z, origin.y);
      if (distance < 0) return groundHit(origin.clone(), 0);
      if (distance > maxDistance) return null;
      return groundHit(new THREE.Vector3(origin.x, origin.y - distance, origin.z), distance);
    }
    const gapAt = (travelled: number) => origin.y + direction.y * travelled
      - groundHeightAt(origin.x + direction.x * travelled, origin.z + direction.z * travelled, origin.y);
    if (gapAt(0) < 0) return groundHit(origin.clone(), 0);
    const steps = Math.max(1, Math.ceil(maxDistance / GROUND_RAY_STEP));
    let low = 0;
    for (let step = 1; step <= steps; step += 1) {
      const high = Math.min(maxDistance, (step * maxDistance) / steps);
      if (gapAt(high) > 0) {
        low = high;
        continue;
      }
      let near = low;
      let far = high;
      for (let refine = 0; refine < GROUND_RAY_REFINEMENTS; refine += 1) {
        const middle = (near + far) / 2;
        if (gapAt(middle) > 0) near = middle;
        else far = middle;
      }
      return groundHit(direction.clone().multiplyScalar(far).add(origin), far);
    }
    return null;
  };

  /**
   * Finite-difference normal, so a wheel on a landuse slope leans with it.
   *
   * Returns a shared scratch vector: this is asked once per collider per tick from the
   * contact path, and four ground samples plus an allocation each time is a real cost at
   * that rate. Callers that keep the answer past their own statement copy it.
   */
  const groundNormalAt = (x: number, z: number, maxHeight: number): THREE.Vector3 => {
    const step = 0.35;
    const dy = groundHeightAt(x + step, z, maxHeight) - groundHeightAt(x - step, z, maxHeight);
    const dz = groundHeightAt(x, z + step, maxHeight) - groundHeightAt(x, z - step, maxHeight);
    return _normal.set(-dy / (2 * step), 1, -dz / (2 * step)).normalize();
  };

  const raycast: PhysicsWorld['raycast'] = (origin, direction, maxDistance, ignore = null, categoryMask = MASK_ALL) => {
    let best = categoryMask === MASK_ALL ? raycastGround(origin, direction, maxDistance) : null;
    for (const body of all) {
      if (body === ignore || !body.colliders.length) continue;
      if ((bodyCategory(body.userData) & categoryMask) === 0) continue;
      const hit = raycastBody(origin, direction, best ? best.distance : maxDistance, body);
      if (hit && (!best || hit.distance < best.distance)) best = hit;
    }
    return best;
  };

  /**
   * Contacts between a body and the terrain, plus the direction the terrain is facing
   * under them, summed into `normalSum` for the caller to average into the manifold's
   * one normal.
   *
   * The normal matters as much as the contact does. Solving every ground contact straight
   * up means a body on a hillside is held up by a force that has no component along the
   * slope: it neither slides nor is slowed climbing, so a landuse bank behaves like a
   * frictionless escalator that carries a car up and never lets gravity pull it back.
   * `depth` is measured vertically because that is what a heightfield gives, and scaled by
   * the normal's own y to turn it into the perpendicular overlap the solver wants.
   */
  const contactAgainstGround = (
    body: RigidBody,
    points: ContactPoint[],
    normalSum: THREE.Vector3,
  ): void => {
    for (const item of body.colliders) {
      if (item.shape.kind === 'box') {
        for (const corner of boxCorners(item, item.shape, body.position, body.quaternion)) {
          const depth = groundHeightAt(corner.x, corner.z, body.aabb.min.y + GROUND_SURFACE_REACH) - corner.y;
          if (depth < -GROUND_CONTACT_SLOP) continue;
          // Sampled under the corner that is touching, not under the collider's centre.
          // Sampling once per collider is four ground queries cheaper, and wrong exactly
          // where it matters: at a height discontinuity — which is what the terrain is
          // made of with the edge slope turned off — a box whose leading corner is buried
          // in a step gets a straight-up normal from its own centre, and drives up the
          // wall instead of being stopped by it.
          const normal = groundNormalAt(corner.x, corner.z, body.aabb.min.y + GROUND_SURFACE_REACH);
          normalSum.add(normal);
          points.push(makeContact(corner, depth * normal.y));
        }
      } else {
        const centre = colliderCentre(item, body.position, body.quaternion, _centre);
        const depth = groundHeightAt(centre.x, centre.z, centre.y - item.shape.radius + GROUND_SURFACE_REACH) - (centre.y - item.shape.radius);
        if (depth < -GROUND_CONTACT_SLOP) continue;
        const normal = groundNormalAt(centre.x, centre.z, centre.y - item.shape.radius + GROUND_SURFACE_REACH);
        normalSum.add(normal);
        // A sphere touches a slope at the point one radius along the surface normal, not
        // straight down — on a bank the difference is where the friction is applied.
        points.push(makeContact(
          centre.clone().addScaledVector(normal, -item.shape.radius),
          depth * normal.y,
        ));
      }
    }
  };

  /**
   * Promotes a struck static prop to dynamic when the momentum arriving along the contact
   * normal exceeds what holds it down. Momentum, not force: what decides whether a bollard
   * survives is how much the thing hitting it weighs and how fast it is going, and that
   * product is exactly an impulse.
   */
  const dislodgeStruckProps = (manifolds: Manifold[]): boolean => {
    let promoted = false;
    for (const manifold of manifolds) {
      const anchored = manifold.a.type === 'static' ? manifold.a
        : manifold.b.type === 'static' ? manifold.b : null;
      const striker = anchored === manifold.a ? manifold.b : manifold.a;
      if (!anchored || anchored === ground || striker.type !== 'dynamic') continue;
      const anchorImpulse = anchored.userData.anchorImpulse;
      const propMass = anchored.userData.mass;
      if (typeof anchorImpulse !== 'number' || typeof propMass !== 'number') continue;

      // Closing speed along the manifold normal, whichever side the static body is on.
      const sign = anchored === manifold.a ? -1 : 1;
      const approach = manifold.normal.dot(striker.linearVelocity) * sign;
      if (approach <= 0) continue;
      if (approach * striker.mass < anchorImpulse) continue;

      setBodyDynamic(anchored, propMass);
      wakeBody(anchored);
      promoted = true;
      for (const listener of dislodgeListeners) listener(anchored);
    }
    return promoted;
  };

  /**
   * How far a body's AABB reaches from its own centre along `direction` — the standard
   * axis-aligned support distance. Used to turn a ray cast from a body's centre into one
   * that effectively starts at its leading face.
   */
  const aabbExtentAlong = (aabb: Aabb, direction: THREE.Vector3): number =>
    Math.abs(direction.x) * (aabb.max.x - aabb.min.x) * 0.5
    + Math.abs(direction.y) * (aabb.max.y - aabb.min.y) * 0.5
    + Math.abs(direction.z) * (aabb.max.z - aabb.min.z) * 0.5;

  /** Centre of a body's AABB — the sweep ray's origin. Not `body.position`: the car's
   * own colliders sit offset above and behind its centre of mass, so the AABB centre is
   * the point the sweep's "extend by half-width" logic actually assumes. */
  const aabbCentre = (aabb: Aabb, target: THREE.Vector3): THREE.Vector3 =>
    target.addVectors(aabb.min, aabb.max).multiplyScalar(0.5);

  /**
   * Stretches a body's broadphase AABB to also cover where this tick's motion will carry
   * it, so a fast mover's pair with a prop that its *current* position doesn't overlap is
   * still generated. Safe to mutate in place: every dynamic body's AABB is rebuilt from
   * its true position by `integratePosition`/`updateBodyDerived` before this is read again.
   */
  const expandAabbAlongVelocity = (aabb: Aabb, velocity: THREE.Vector3, dt: number): void => {
    const dx = velocity.x * dt;
    const dy = velocity.y * dt;
    const dz = velocity.z * dt;
    if (dx < 0) aabb.min.x += dx; else aabb.max.x += dx;
    if (dy < 0) aabb.min.y += dy; else aabb.max.y += dy;
    if (dz < 0) aabb.min.z += dz; else aabb.max.z += dz;
  };

  /**
   * Ray-swept fallback for a fast mover the discrete test found nothing for. A single ray
   * from the mover's AABB centre (`moverOrigin`, taken before this tick's motion), extended
   * by that AABB's own extent along its motion (`moverExtent`) so it effectively starts at
   * the leading face, is enough for the car-vs-thin-prop case this exists for (see
   * docs/misc/svartaksidocs/swept-collision.md) without a full swept-volume test. Returns null
   * when the ray misses, or when it hits beyond this tick's travel (nothing to correct yet
   * — the discrete test will catch it honestly next tick).
   */
  const sweepManifold = (
    mover: RigidBody,
    other: RigidBody,
    moverOrigin: THREE.Vector3,
    moverExtent: number,
    dt: number,
  ): Manifold | null => {
    const speed = mover.linearVelocity.length();
    if (speed < 1e-4) return null;
    const direction = _sweepDirection.copy(mover.linearVelocity).multiplyScalar(1 / speed);
    const motion = speed * dt;
    const hit = raycastBody(moverOrigin, direction, motion + moverExtent, other);
    if (!hit) return null;
    const penetration = motion - (hit.distance - moverExtent);
    if (penetration <= 0) return null;
    return {
      a: other,
      b: mover,
      normal: hit.normal,
      points: [makeContact(hit.point, penetration)],
      friction: Math.sqrt(other.friction * mover.friction),
      restitution: Math.max(other.restitution, mover.restitution),
    };
  };

  return {
    gravity,
    ground,
    addBody(body) {
      all.push(body);
      updateBodyDerived(body);
      staticsDirty = true;
    },
    removeBody(body) {
      const index = all.indexOf(body);
      if (index >= 0) all.splice(index, 1);
      staticsDirty = true;
    },
    removeLayer(layer) {
      for (let index = all.length - 1; index >= 0; index -= 1) {
        if (all[index].userData.layer === layer) all.splice(index, 1);
      }
      staticsDirty = true;
    },
    bodies: () => all,
    manifolds: () => solved,
    setGroundHeight(height) {
      groundHeight = height;
    },
    groundHeightAt,
    raycast,
    addVehicle(vehicle) {
      vehicles.push(vehicle);
    },
    removeVehicle(vehicle) {
      const index = vehicles.indexOf(vehicle);
      if (index >= 0) vehicles.splice(index, 1);
    },
    onDislodge(listener) {
      dislodgeListeners.push(listener);
    },
    step(dt) {
      if (!(dt > 0)) return;
      // A prop promoted mid-tick stays in the static index until here — the one reindex
      // per step, at the top, before anything reads either list. Nothing between steps
      // touches the broadphase (raycast walks every body), so there is no second one.
      if (staticsDirty) reindex();

      for (const body of dynamics) integrateVelocity(body, gravity, dt);
      for (const vehicle of vehicles) {
        vehicle.update(dt, (origin, direction, maxDistance, ignore) =>
          raycast(origin, direction, maxDistance, ignore));
      }

      const manifolds: Manifold[] = [];
      // The car is the only body fast enough to tunnel through a thin static prop between
      // ticks (boost tops out at 150 m/s = 2.5m/tick, well past a 0.2-0.3m lamp post).
      // Its broadphase AABB is stretched along this tick's motion so a prop its
      // *pre-move* position doesn't overlap still generates a pair, and it gets a ray-swept
      // fallback below when the discrete test — which only sees whether bodies overlap
      // *now* — finds nothing. See docs/misc/svartaksidocs/swept-collision.md.
      const fastMovers = new Map<RigidBody, { origin: THREE.Vector3; extent: number }>();
      for (const body of dynamics) {
        if (body.sleeping || body.userData.kind !== 'car') continue;
        const speed = body.linearVelocity.length();
        if (speed <= sweepThreshold) continue;
        const direction = _sweepDirection.copy(body.linearVelocity).multiplyScalar(1 / speed);
        fastMovers.set(body, {
          origin: aabbCentre(body.aabb, new THREE.Vector3()),
          extent: aabbExtentAlong(body.aabb, direction),
        });
        expandAabbAlongVelocity(body.aabb, body.linearVelocity, dt);
      }

      for (const pair of broadphase.pairs(dynamics)) {
        if (pair.a.sleeping && (pair.b.sleeping || pair.b.type === 'static')) continue;
        // Category/mask filter (backlog item 4): a positionally-driven body that opts out
        // of solid collision — the bus is steered onto its route, not by contact forces —
        // is excluded here rather than by leaving it out of the broadphase, so it still
        // gets manifolds against whatever *is* in its mask (a car pulling out in front of
        // it, say) without a building's static frame fighting the spline that drives it.
        if (!categoriesInteract(pair.a.userData, pair.b.userData)) continue;
        const before = manifolds.length;
        collideBodies(pair.a, pair.b, manifolds);
        if (manifolds.length > before) continue;
        const mover = fastMovers.has(pair.a) ? pair.a : fastMovers.has(pair.b) ? pair.b : null;
        if (!mover) continue;
        const other = mover === pair.a ? pair.b : pair.a;
        const { origin, extent } = fastMovers.get(mover)!;
        const swept = sweepManifold(mover, other, origin, extent, dt);
        if (swept) manifolds.push(swept);
      }
      if (dislodgeStruckProps(manifolds)) staticsDirty = true;

      for (const body of dynamics) {
        if (body.sleeping) continue;
        const points: ContactPoint[] = [];
        const normalSum = new THREE.Vector3();
        contactAgainstGround(body, points, normalSum);
        if (!points.length) continue;
        // One normal for the whole patch: the average of the surface under each contact.
        // A body spanning a crest is standing on two slopes and can only be given one
        // answer, and the average is the plane it is actually resting on.
        const normal = normalSum.lengthSq() > 1e-9
          ? normalSum.normalize()
          : new THREE.Vector3(0, 1, 0);
        manifolds.push({
          a: ground,
          b: body,
          normal,
          points,
          friction: Math.sqrt(ground.friction * body.friction),
          restitution: Math.max(ground.restitution, body.restitution) * 0.5,
        });
      }

      previousImpulses = solveContacts(manifolds, dt, iterations, previousImpulses);
      solved = manifolds;

      for (const body of dynamics) {
        integratePosition(body, dt);
        updateSleep(body, dt);
      }
    },
  };
}

// Scratch for the per-tick ground path: the finite-difference normal and the collider
// centre it is sampled at. Neither outlives the statement that asks for it.
const _normal = new THREE.Vector3();
const _centre = new THREE.Vector3();
const _sweepDirection = new THREE.Vector3();
